# Generated by Django 4.2.7 on 2023-12-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_card_cart_rename_carditem_cartitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
